// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://drstxjrzhyfxojrabxkf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRyc3R4anJ6aHlmeG9qcmFieGtmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2NTIwODEsImV4cCI6MjA2NDIyODA4MX0.8L9haH6b931euUx6LARQad1a0jH4-OSxuX_P8f1TXj8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);